// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_XU80dXXjfP_06Uv9JTDe2aMdNqjpbY',
    appId: '1:112269723382:web:402593f11b0afba89a8ed7',
    messagingSenderId: '112269723382',
    projectId: 'madridmug',
    authDomain: 'madridmug.firebaseapp.com',
    storageBucket: 'madridmug.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpLdCLqjcgI6fYE-YMiyMdCguFjv0D0-s',
    appId: '1:112269723382:android:8543865e76fc7fe29a8ed7',
    messagingSenderId: '112269723382',
    projectId: 'madridmug',
    storageBucket: 'madridmug.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfvjicTmgFWkcKBlBA-B63rVr1HDN5T6g',
    appId: '1:112269723382:ios:dee73480dfdd453d9a8ed7',
    messagingSenderId: '112269723382',
    projectId: 'madridmug',
    storageBucket: 'madridmug.appspot.com',
    androidClientId: '112269723382-8kmdjgejm0t7qf3he7qsm6qeb7qpqgcn.apps.googleusercontent.com',
    iosClientId: '112269723382-2liatfcvdcq2eb9r72ckeslob7qkudhh.apps.googleusercontent.com',
    iosBundleId: 'es.etsisi.mad.madridmug.madridmugFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfvjicTmgFWkcKBlBA-B63rVr1HDN5T6g',
    appId: '1:112269723382:ios:dee73480dfdd453d9a8ed7',
    messagingSenderId: '112269723382',
    projectId: 'madridmug',
    storageBucket: 'madridmug.appspot.com',
    androidClientId: '112269723382-8kmdjgejm0t7qf3he7qsm6qeb7qpqgcn.apps.googleusercontent.com',
    iosClientId: '112269723382-2liatfcvdcq2eb9r72ckeslob7qkudhh.apps.googleusercontent.com',
    iosBundleId: 'es.etsisi.mad.madridmug.madridmugFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2_XU80dXXjfP_06Uv9JTDe2aMdNqjpbY',
    appId: '1:112269723382:web:31c2c708e33dc3099a8ed7',
    messagingSenderId: '112269723382',
    projectId: 'madridmug',
    authDomain: 'madridmug.firebaseapp.com',
    storageBucket: 'madridmug.appspot.com',
  );

}


